# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:
  datasource:
    username: root
    password:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: OTZmZDAwYzNjNjQ2MWMzYWI2NDQxNjA3MTMzOTRiNTZlOWVkNzZiNTk3OTZiMDc5MWQzYjFhZjdjZjI3MzUxZTlhNmI2Yjg0OGUxMTE3NDIzODhhYWM4NWYxMDhiNmI0N2Q4YmMxNDM0MmE1ZDFiNzM3MTNlMzFmYTBmYjAwNjg=
