package com.udea.proyecto.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AvionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAvionAllPropertiesEquals(Avion expected, Avion actual) {
        assertAvionAutoGeneratedPropertiesEquals(expected, actual);
        assertAvionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAvionAllUpdatablePropertiesEquals(Avion expected, Avion actual) {
        assertAvionUpdatableFieldsEquals(expected, actual);
        assertAvionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAvionAutoGeneratedPropertiesEquals(Avion expected, Avion actual) {
        assertThat(actual)
            .as("Verify Avion auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAvionUpdatableFieldsEquals(Avion expected, Avion actual) {
        assertThat(actual)
            .as("Verify Avion relevant properties")
            .satisfies(a -> assertThat(a.getModelo()).as("check modelo").isEqualTo(expected.getModelo()))
            .satisfies(a -> assertThat(a.getCapacidad()).as("check capacidad").isEqualTo(expected.getCapacidad()))
            .satisfies(a -> assertThat(a.getMatricula()).as("check matricula").isEqualTo(expected.getMatricula()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAvionUpdatableRelationshipsEquals(Avion expected, Avion actual) {
        // empty method
    }
}
